import 'package:flutter/material.dart';
import 'data/cobrapp_repository.dart';

class PortfolioPage extends StatefulWidget { const PortfolioPage({super.key}); @override State<PortfolioPage> createState()=>_PortfolioPageState(); }
class _PortfolioPageState extends State<PortfolioPage> {
  late Future<Map<String,dynamic>> future;
  @override void initState(){super.initState();future=_load();}
  double n(dynamic v)=>v is num?v.toDouble():double.tryParse('$v')??0;
  String money(double v){final s=v.toStringAsFixed(2).replaceAll('.',',');final a=s.split(',');var i=a[0];final neg=i.startsWith('-');if(neg)i=i.substring(1);final g=<String>[];for(var x=i.length;x>0;x-=3){final st=x-3<0?0:x-3;g.insert(0,i.substring(st,x));}return '${neg?'-':''}R\\$ ${g.join('.').isEmpty?'0':g.join('.')}';}
  Future<Map<String,dynamic>> _load() async {
    final repo=CobrAppRepository();
    final loans=List<Map<String,dynamic>>.from(await repo.db.from('cobrapp_loans').select('id,customer_id,principal,total_amount,status,created_at,cobrapp_customers(name)').eq('user_id',repo.uid).order('created_at',ascending:false));
    final installments=List<Map<String,dynamic>>.from(await repo.db.from('cobrapp_installments').select('id,loan_id,customer_id,amount,paid_amount,interest_amount,interest_paid,status,due_date').eq('user_id',repo.uid).order('due_date'));
    final payments=List<Map<String,dynamic>>.from(await repo.db.from('cobrapp_payments').select('amount,paid_at,type,customer_id').eq('user_id',repo.uid).order('paid_at',ascending:false));
    final expenses=List<Map<String,dynamic>>.from(await repo.db.from('cobrapp_expenses').select('amount,spent_at').eq('user_id',repo.uid).order('spent_at',ascending:false));
    final active=loans.where((x)=>x['status']=='active').toList();final ids=active.map((x)=>x['id'].toString()).toSet();final ai=installments.where((x)=>ids.contains(x['loan_id']?.toString())).toList();
    final principal=active.fold(0.0,(a,x)=>a+n(x['principal']));final total=active.fold(0.0,(a,x)=>a+n(x['total_amount']));final interest=(total-principal).clamp(0,double.infinity).toDouble();
    final pending=ai.fold(0.0,(a,x)=>a+(n(x['amount'])-n(x['paid_amount'])).clamp(0,double.infinity));
    final today=DateTime.now();final overdue=ai.where((x)=>x['status']!='paid'&&DateTime.tryParse('${x['due_date']}')?.isBefore(DateTime(today.year,today.month,today.day))==true).fold(0.0,(a,x)=>a+(n(x['amount'])-n(x['paid_amount'])).clamp(0,double.infinity));
    final received=payments.fold(0.0,(a,x)=>a+n(x['amount']));final expenseTotal=expenses.fold(0.0,(a,x)=>a+n(x['amount']));
    final projectedNet=interest-expenseTotal;
    final months=<Map<String,dynamic>>[];
    for(var offset=5;offset>=0;offset--){final d=DateTime(today.year,today.month-offset,1);final next=DateTime(d.year,d.month+1,1);double loaned=0,pay=0,expense=0;for(final x in loans){final c=DateTime.tryParse('${x['created_at']}');if(c!=null&&!c.isBefore(d)&&c.isBefore(next))loaned+=n(x['principal']);}for(final x in payments){final c=DateTime.tryParse('${x['paid_at']}');if(c!=null&&!c.isBefore(d)&&c.isBefore(next))pay+=n(x['amount']);}for(final x in expenses){final c=DateTime.tryParse('${x['spent_at']}');if(c!=null&&!c.isBefore(d)&&c.isBefore(next))expense+=n(x['amount']);}months.add({'label':'${d.month.toString().padLeft(2,'0')}/${d.year.toString().substring(2)}','loaned':loaned,'received':pay,'expense':expense});}
    return {'principal':principal,'interest':interest,'total':total,'pending':pending,'overdue':overdue,'received':received,'expenses':expenseTotal,'projectedNet':projectedNet,'rate':principal<=0?0:(interest/principal)*100,'loans':active.length,'months':months};
  }
  @override Widget build(BuildContext context){return FutureBuilder<Map<String,dynamic>>(future:future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Não foi possível carregar a carteira.\\n${s.error}'));final d=s.data!;final cs=Theme.of(context).colorScheme;final months=List<Map<String,dynamic>>.from(d['months']);return RefreshIndicator(onRefresh:()async=>setState(()=>future=_load()),child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(16,12,16,28),children:[Text('Gestão da Carteira',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Visão completa do dinheiro na rua, juros, lucro projetado, recebimentos e risco da carteira.'),const SizedBox(height:18),_Hero(title:'Total da carteira',value:money(n(d['total'])),subtitle:'${money(n(d['principal']))} de capital + ${money(n(d['interest']))} de juros previstos',colors:[cs.primary,const Color(0xFFA855F7)]),const SizedBox(height:12),_Grid(cards:[_M('Na rua',money(n(d['principal'])),'Capital emprestado',Icons.trending_up_rounded,cs.primary),_M('Juros previstos',money(n(d['interest'])),'Receita projetada',Icons.percent_rounded,const Color(0xFF7C3AED)),_M('Capital recebido',money(n(d['received'])-n(d['interest'])), 'Estimativa de principal recuperado',Icons.account_balance_rounded,const Color(0xFF2563EB)),_M('Juros recebidos',money(n(d['received'])>0?n(d['received']):0),'Total de pagamentos recebidos',Icons.payments_rounded,const Color(0xFF16A34A)),_M('Inadimplência',money(n(d['overdue'])),'Saldo vencido',Icons.warning_amber_rounded,const Color(0xFFDC2626)),_M('Lucro previsto',money(n(d['projectedNet'])),'Juros previstos menos despesas',Icons.auto_graph_rounded,const Color(0xFFEA580C))]),const SizedBox(height:12),Card(child:ListTile(title:const Text('Taxa da carteira',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${n(d['loans']).toInt()} empréstimos ativos'),trailing:Text('${n(d['rate']).toStringAsFixed(1).replaceAll('.',',')}%',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)))),const SizedBox(height:20),Text('Evolução dos últimos 6 meses',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:10),Card(child:Padding(padding:const EdgeInsets.all(16),child:_Chart(months:months))),const SizedBox(height:8),const Text('Barras: emprestado, recebido e despesas. Os valores são calculados diretamente do banco.',textAlign:TextAlign.center,style:TextStyle(fontSize:12))]));}
}
class _Grid extends StatelessWidget{final List<Widget> cards;const _Grid({required this.cards});@override Widget build(BuildContext c){return Wrap(spacing:10,runSpacing:10,children:cards.map((x)=>SizedBox(width:(MediaQuery.sizeOf(c).width-42)/2,child:x)).toList());}}
class _M extends StatelessWidget{final String t,v,sub;final IconData i;final Color c;const _M(this.t,this.v,this.sub,this.i,this.c);@override Widget build(BuildContext x)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(backgroundColor:c.withValues(alpha:.12),child:Icon(i,color:c)),const SizedBox(height:9),Text(t,style:Theme.of(x).textTheme.bodySmall),const SizedBox(height:3),FittedBox(alignment:Alignment.centerLeft,child:Text(v,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))),const SizedBox(height:3),Text(sub,style:Theme.of(x).textTheme.bodySmall)])));
class _Hero extends StatelessWidget{final String title,value,subtitle;final List<Color> colors;const _Hero({required this.title,required this.value,required this.subtitle,required this.colors});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:LinearGradient(colors:colors)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.account_balance_wallet_rounded,color:Colors.white),const SizedBox(height:12),Text(title,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(value,style:const TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(subtitle,style:const TextStyle(color:Colors.white70))]));}
class _Chart extends StatelessWidget{final List<Map<String,dynamic>> months;const _Chart({required this.months});double n(dynamic v)=>v is num?v.toDouble():0;@override Widget build(BuildContext c){final maxV=months.fold<double>(1,(m,x)=>[m,n(x['loaned']),n(x['received']),n(x['expense'])].reduce((a,b)=>a>b?a:b));return SizedBox(height:230,child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:months.map((m){final vals=[n(m['loaned']),n(m['received']),n(m['expense'])];return Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:Column(mainAxisAlignment:MainAxisAlignment.end,children:[Expanded(child:Row(crossAxisAlignment:CrossAxisAlignment.end,children:vals.map((v)=>Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:1),child:Container(height:150*(v/maxV),decoration:BoxDecoration(color:vals.indexOf(v)==0?const Color(0xFF7C3AED):vals.indexOf(v)==1?const Color(0xFF16A34A):const Color(0xFFDC2626),borderRadius:const BorderRadius.vertical(top:Radius.circular(5))))))).toList())),const SizedBox(height:6),Text('${m['label']}',style:const TextStyle(fontSize:10))])));}).toList()));}}
